name: Run WhatsApp Group Name Scraper

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Run script
        run: python whatsapp_group_name_scraper.py
